# This setting allows these values to merge into the settings, because by default this
# file will overwrite all settings in the same group names in the main 'settings.toml'
# file. It is REQUIRED that this setting stay 'true' so as not to completely overwrite all
# other settings.
dynaconf_merge = true

[Weather_Widget]
    # This is where you should specify your openweathermap API key.
    # Get a free API key by creating an account here: https://openweathermap.org/api
    # This value will default to my API key if not specified, but is is 
    # greatly encouraged that you get your own so all users can have a good experience.
    api_key = ""

[To_Do_Widget]
    # This is where your Microsoft app ID should be specified. 
    # Eventually, I am going to look into a way where an end user
    # will not need to specify this, but for now, it is necessary.
    # This will also default to my app id if not specified, but I DO NOT know if that works.
    # Check out the following page for more help with this:
    # https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
    app_id = ""

[Spotify_Widget]
    client_id = ""
    client_secret = ""