# This setting allows these values to merge into the settings, because by default this
# file will overwrite all settings in the same group names in the main 'settings.toml'
# file. It is REQUIRED that this setting stay 'true' so as not to completely overwrite all
# other settings.
dynaconf_merge = true

[Weather_Widget]
    # This is where you should specify your openweathermap API key.
    # Get a free API key by creating an account here: https://openweathermap.org/api
    # Also check out https://github.com/Bennett-Wendorf/Kivy-Raspi-Desktop-App/wiki/Getting-Started#14-set-up-openweathermap-api-key for more info
    api_key = ""

[To_Do_Widget]
    # This is where your Microsoft app ID should be specified.
    # Check out my wiki https://github.com/Bennett-Wendorf/Kivy-Raspi-Desktop-App/wiki/Getting-Started#15-set-up-microsoft-app-id for help with this
    # Check out the following page for more help with this:
    # https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
    #app_id = ""

[Spotify_Widget]
    # This is where Spotify API information should be specified. 
    # Check out my wiki article for how to do this https://github.com/Bennett-Wendorf/Kivy-Raspi-Desktop-App/wiki/Set-up-Spotify-API
    # Also see https://developer.spotify.com/documentation/web-api/quick-start/ for more info
    client_id = ""
    client_secret = ""