[Weather_Widget]
    # This is where you should specify your openweathermap API key.
    # Get a free API key by creating an account here: https://openweathermap.org/api
    # This value will default to my API key if not specified, but is is 
    # greatly encouraged that you get your own so all users can have a good experience.
    api_key = ""